[package]
name = "lasync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbfr = { path = "/home/ocing86/Documents/works/coding/rust/mylib/cbfr/" }
